'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EngManagerAgreement

    '''<summary>
    '''EngTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EngTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EngButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EngButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''eng_man_approval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eng_man_approval As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''EngBtnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EngBtnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''EngDisplayDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EngDisplayDatabase As Global.System.Web.UI.WebControls.GridView
End Class
